{{- if .Values.gcp.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: cluster-services
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.gcpProjectId | required "gcp.gcpProjectId is required" }}
      # No auth block - uses Application Default Credentials (ADC)
      # The VM instance identity will be used automatically
{{- end }}

