apiVersion: v2
name: kibana
description: Kibana for log visualization and analysis
type: application
version: 0.1.0
appVersion: "9.1.2"
dependencies:
  - name: kibana
    version: "12.1.10"
    repository: https://charts.bitnami.com/bitnami
