replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

elasticsearch:
  hosts:
    - elasticsearch-master
  port: 9200
  tls:
    enabled: false

extraConfiguration:
  kibana.yml: |
    server.host: "0.0.0.0"
    xpack.security.enabled: false

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: false
