apiVersion: v2
name: cert-manager
description: Certificate management controller for Kubernetes
type: application
version: 1.0.0
appVersion: "1.13.0"
dependencies:
  - name: cert-manager
    version: "1.13.3"
    repository: https://charts.jetstack.io
