replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

image:
  debug: true

service:
  type: ClusterIP
  ports:
    beats:
      port: 5044
      targetPort: 5044
      protocol: TCP

persistence:
  enabled: false

input: |
  beats {
    port => 5044
  }

output: |
  elasticsearch {
    hosts => ["elasticsearch-master:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    ssl => false
    ssl_certificate_verification => false
  }
