apiVersion: v2
name: external-secrets
description: External Secrets Operator for syncing secrets from external providers
type: application
version: 1.0.0
appVersion: "0.9.0"
dependencies:
  - name: external-secrets
    version: "0.9.11"
    repository: https://charts.external-secrets.io
