[all]
master-01 ansible_host=10.10.10.3 ip=10.10.10.3 ansible_port=22 ansible_user=talha_demir_mail_gmail_com ansible_become=true etcd_member_name=master-01
worker-01 ansible_host=10.10.10.2 ip=10.10.10.2 ansible_port=22 ansible_user=talha_demir_mail_gmail_com ansible_become=true
worker-02 ansible_host=10.10.10.4 ip=10.10.10.4 ansible_port=22 ansible_user=talha_demir_mail_gmail_com ansible_become=true

[kube_control_plane]
master-01

[etcd]
master-01

[kube_node]
worker-01
worker-02

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr

[k8s_cluster:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -o StrictHostKeyChecking=no talha_demir_mail_gmail_com@34.40.109.211" -o StrictHostKeyChecking=no'

[bastion]
bastion ansible_host=34.40.109.211 ansible_port=22 ansible_user=talha_demir_mail_gmail_com ansible_become=true
