apiVersion: v2
name: elasticsearch
description: Elasticsearch for log storage and search
type: application
version: 0.1.0
appVersion: "8.11.0"
dependencies:
  - name: elasticsearch
    version: "19.10.0"
    repository: https://helm.elastic.co

