global:
  kibanaEnabled: false

master:
  replicas: 1
  heapSize: 3g
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 6Gi
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 20Gi

data:
  replicas: 0
coordinating:
  replicas: 0
ingest:
  replicas: 0

security:
  enabled: false
  tls:
    enabled: false

extraConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false

service:
  type: ClusterIP
